# Generated by Django 4.2.30 on 2026-09-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_citizen_is_approved_complaint_assigned_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='security_answer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='citizen',
            name='security_question',
            field=models.CharField(choices=[('pet', 'What was the name of your first pet?'), ('school', 'What was the name of your first school?'), ('city', 'What city were you born in?'), ('nickname', 'What was your childhood nickname?')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='complaint',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='progress_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='progress_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='security_answer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='officer',
            name='security_question',
            field=models.CharField(choices=[('pet', 'What was the name of your first pet?'), ('school', 'What was the name of your first school?'), ('city', 'What city were you born in?'), ('nickname', 'What was your childhood nickname?')], default='', max_length=30),
        ),
    ]
